### ISSUE TITLE
KAboutData QML Singleton registration may not be needed

### ISSUE THREAD

**Issue by redstrate** [mystchonky/cxx-kde-frameworks#1]
I see this function: https://github.com/mystchonky/cxx-kde-frameworks/blob/8aeafd338c27d4072e05e62ee2ed91417681e6b5/src/kcoreaddons/kaboutdata.rs#L90

Did you know I added a singleton to the existing KCoreAddons QML plugin? In this [commit](https://invent.kde.org/frameworks/kcoreaddons/-/commit/c53eeac32da84854ac65deddbf839983078ed456). We can probably strip that and reduce the code size a little bit.

**Comment by dphaldes** [comment]
You are right! It does work automatically without manual registration if KCoreAddons is imported on qml side. I wasn't aware of this as I have very little knowledge of this and was using Kontrast as a point of reference. I shall remove the extra code.
